name: 'Setup docker buildx'
description: 'Setup docker buildx'

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true

    # Release version setup
    - uses: ./.github/actions/get-release-version
